### ISSUE TITLE
SOLOV2 postprocess discussion

### ISSUE THREAD

**Issue by qin2294096** [WXinlong/SOLO#100]
Hi, Xinlong. As SOLOV2 paper, Matrix NMS is a very good postprocessing method for box-free segmentation models. It outperforms the other NMS methods in both speed and accuracy.

However, before doing Matrix NMS, we need to prepare atmost 500 masks of 1/4 image resolution. This seems to cost much time in crowded scenes. Perhaps the cost of box-NMS is lower than mask-NMS when objects number is large. What do you think about this? Thanks.

**Comment by WXinlong** [comment]
@qin2294096  Yes, when the number of objects is very large, box NMS is more computational friendly.

**Comment by qin2294096** [comment]
Thank you for the reply
