### ISSUE TITLE
how to handle center failing into same grid? 

### ISSUE THREAD

**Issue by ysyyork** [WXinlong/SOLO#101]
i got a bit confused on how to handle center falling into same grid cases. For eg, if I have two objects overlapping with each other and with same size and shape but in "x" way. Like I have two pens but I put them  as this "x" shape. then both pen will get two parts as segmentation labels and the mass center will be in the center of this "x" shape. in this case, how I should construct the gt? it seems solo by nature can't resolve this issue no matter how big the grid size you set? is that true or I missed anything here?

**Comment by WXinlong** [comment]
@ysyyork  We do not consider the "x" case. It is a corner case for almost all the existing instance segmentation methods. As for other cases that two centers fall into the same grid, please refer to #20 .
