### ISSUE TITLE
Single class Datasets on SOLO 

### ISSUE THREAD

**Issue by Chenyusheng97** [WXinlong/SOLO#119]

**Comment by Chenyusheng97** [comment]
I fix the bug by 
    def load_annotations(self, ann_file):
        self.coco = COCO(ann_file)
        self.cat_ids = self.coco.getCatIds()
        self.cat2label = {
            cat_id: i+1    # fix  cat_id: i   
            for i, cat_id in enumerate(self.cat_ids)
        }
        self.img_ids = self.coco.getImgIds()
        img_infos = []
        for i in self.img_ids:
            info = self.coco.loadImgs([i])[0]
            info['filename'] = info['file_name']
            img_infos.append(info)
        return img_infos

**Comment by ojotoxy** [comment]
@Chenyusheng97  Which lines did you change? Can you make the diff a little bit more clear? What do you think was wrong? Thanks

**Comment by peterwkl2013** [comment]
yes, this is a bug for 1 class, fixed by:

        if len(self.cat_ids) > 2:
            self.cat2label = {
                cat_id: i + 1
                for i, cat_id in enumerate(self.cat_ids)
            }
        else:
            #for 1 class
            self.cat2label = {
                cat_id: i
                for i, cat_id in enumerate(self.cat_ids)
            }
