### ISSUE TITLE
from . import nms_cpu, nms_cuda from .soft_nms_cpu import soft_nms_cpu

### ISSUE THREAD

**Issue by Shanyaodedanshen** [WXinlong/SOLO#122]
from . import nms_cpu, nms_cuda
from .soft_nms_cpu import soft_nms_cpu

help

git clone https://github.com/WXinlong/SOLO.git
cd SOLO
pip install -r requirements/build.txt
pip install "git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI"
pip install -v -e . 

I have successfully installed these command，however, there are no nms_cpu, nms_cuda or soft_nms_cpu.

Backend:
pytorch1.1.0

**Comment by Shanyaodedanshen** [comment]
win10

**Comment by Shanyaodedanshen** [comment]
I didn't make sure the version of cuda in conda virtual envrionment. I setup pytorch based on the version of cuda in local. Now it's working.

**Comment by yeungkong** [comment]
@Shanyaodedanshen I am facing the same problem. Could you please specify how you fix this?

**Comment by Shanyaodedanshen** [comment]
> @Shanyaodedanshen I am facing the same problem. Could you please specify how you fix this?

make sure ur cuda version matches the pytorch version.
