### ISSUE TITLE
I successfully trained my own data set, but during the test I found that the category of the test image is still the category of COCO, not the category of my data set

### ISSUE THREAD

**Issue by caoccp** [WXinlong/SOLO#126]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python tools/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by talebolano** [comment]
@caoccp do you use tools/test_ins_ap.py for test? accoring this [line](https://github.com/WXinlong/SOLO/blob/master/tools/test_ins_vis.py#L26),you may write your class name [here](https://github.com/WXinlong/SOLO/blob/4c0c4c2631d625f0a9e0e73a716a87ae679b31f1/mmdet/core/evaluation/class_names.py#L92)

**Comment by caoccp** [comment]
> @caoccp使用工具/工具test_ins_ap.py测试？根据这条线[，](https://github.com/WXinlong/SOLO/blob/master/tools/test_ins_vis.py#L26)你可以在这里写你的班级[名称](https://github.com/WXinlong/SOLO/blob/4c0c4c2631d625f0a9e0e73a716a87ae679b31f1/mmdet/core/evaluation/class_names.py#L92)
Thank you very much, I have solved this problem
