### ISSUE TITLE
KeyError: 'SOLO is not in the detector registry'

### ISSUE THREAD

**Issue by GittersYang** [WXinlong/SOLO#134]
i can't train the SOLO
thank you

**Comment by WXinlong** [comment]
@GittersYang  What did you modify?

**Comment by GittersYang** [comment]
我最开始是在mmdetection环境下运行，后来发现需要单独安装solo环境，因为会solo会替换mm里的一些包

**Comment by StarPlatinum2020** [comment]
你好，关于solo程序上'SOLO is not in the detector registry' 的这个问题有解决吗，万分感谢

**Comment by xuhao-anhe** [comment]
> 你好，关于solo程序上'SOLO is not in the detector registry' 的这个问题有解决吗，万分感谢

你好，我也遇到这个问题了，请问你解决了吗
