### ISSUE TITLE
Question about the avg_factor in category loss.

### ISSUE THREAD

**Issue by charlesCXK** [WXinlong/SOLO#140]
Dear author,
Thanks for your generous sharing! When trying to understand your code, I have a question about the sigmoid focal loss that used to supervise the category classification. The loss value is averaged by the number of positive samples. Since the loss is calculated on all the samples (positive && negative), why not divide it by the number of all the samples?

Hoping for your reply, thank you!

**Comment by taokong** [comment]
Here we just follow the default settings of the Focal Loss paper (https://arxiv.org/abs/1708.02002)
