### ISSUE TITLE
How to train with other Dataset format ？

### ISSUE THREAD

**Issue by Johnson-yue** [WXinlong/SOLO#144]
Hi， If I have pair dataset， like （image， mask） and I want to train solov2 for segmentation task。 How should I train with my dataset？

**Comment by WXinlong** [comment]
@Johnson-yue  You are suggested to convert your dataset to COCO-style format.

**Comment by Johnson-yue** [comment]
ok, thank you I will do it

**Comment by lxwkobe24** [comment]
> ok, thank you I will do it

success?could you tell how to convert? thanks!
