### ISSUE TITLE
Question about Matrix NMS time measurement

### ISSUE THREAD

**Issue by dps42** [WXinlong/SOLO#150]
Hi. I'm reading your SOLOv2 paper, which says Matrix NMS takes < 1 ms.
How was the timing measured?

"For usage, we just need thresholding and selecting top-k scoring masks as the final predictions."

Does the < 1ms measurement include both thresholding and selecting top-k scoring masks too? (I think top-k is max_per_img = 100).

Or does it only include what's in "def matrix_nms()" in https://github.com/WXinlong/SOLO/blob/04c9c42803c3341b8f31b6e9ed0f5d32b7aee72a/mmdet/core/post_processing/matrix_nms.py ? If yes, what's the overall timing for the whole NMS process?

Thanks.

**Comment by zzzzzz0407** [comment]
We return None before NMS for simplicity, therefore, I think the time including matrix nms / thresholding and selecting top-k scoring masks.

**Comment by dps42** [comment]
thank you for the response. < 1ms measurement for everything seems incredibly fast.
