### ISSUE TITLE
Fps on 1080 video 

### ISSUE THREAD

**Issue by Auth0rM0rgan** [WXinlong/SOLO#17]
Hey @WXinlong, well done and thanks for sharing. I have a question about SoloV1 since SoloV2 is not published yet. 
 -- which one of the pretrained models is suitable to get a high Fps ( around ~30Fps) on 1080p videos? Is it possible to reach to ~30 fps with the lightweight models?

Thanks!

**Comment by WXinlong** [comment]
@Auth0rM0rgan    The model "Decoupled_SOLO_Light_R50_3x"  runs at 34 fps on a V100 GPU for input images being resized to about 512.  You can directly use that model to inference on your 1080p video, but the proccessed input will be resized in fact.   If you want to use the real 1080p input size as the model input, it might be too large and should largely slow the inference.   

But I will upload more faster and better models  and hope they could help.
