### ISSUE TITLE
error: command '***' failed with exit status 1　solutions

### ISSUE THREAD

**Issue by ssocean** [WXinlong/SOLO#172]
![image](https://user-images.githubusercontent.com/48676611/118434285-60b81000-b70f-11eb-852e-62470542a871.png)
I've figured out how to solve the problem "failed with exit status 1" on Ubuntu

**Comment by ssocean** [comment]
follow the instructions of rfezzani　https://github.com/WXinlong/SOLO/issues/151#issuecomment-784971764　. for me, only 'conda install gxx_linux-64 -y' is used.

**Comment by ssocean** [comment]
then type 'pip install -v -e .' in the console and wait for error warning. 
![image](https://user-images.githubusercontent.com/48676611/118434944-7e39a980-b710-11eb-8c68-32ca53becdbd.png)
find the file marked by the red box on your device. and then follow the instructions of https://github.com/WXinlong/SOLO/issues/151#issuecomment-780299922

**Comment by hushunda** [comment]
me too

**Comment by ssocean** [comment]
> me too

你按着我上面写的一步一步来改应该就可以了。我这个不是个问题，更像个教程。如果你看不懂的话，我待会写个中文版的，在下面。

**Comment by ssocean** [comment]
如果你出现了这个问题：error: command '***' failed with exit status 1
首先，看看里面有没有gcc相关的报错，如果有的话，你要先安装gcc。https://github.com/WXinlong/SOLO/issues/151#issuecomment-784971764 这个评论写的很详细，对于我的环境来说，一些基本条件已经满足了，所以我只用了“conda install gxx_linux-64 -y” 这一条命令。
接着，运行“pip install -v -e .”这个命令。不出意外的话，会报错。注意仔细看报错的提示，找到上图红框圈出的 */*.cpp的这个c++文件,按照 https://github.com/WXinlong/SOLO/issues/151#issuecomment-780299922 的提示把这个文件里面里面所有的AT_CHECK ctrl+h替换成TORCH_CHECK。一共会需要改好几个这样的文件，注意找这个文件就可以了。

**Comment by hushunda** [comment]
> > me too
> 
> 你按着我上面写的一步一步来改应该就可以了。我这个不是个问题，更像个教程。如果你看不懂的话，我待会写个中文版的，在下面。

谢谢！我按照上面步骤。安装成功了。
