### ISSUE TITLE
the inference time cost two much?

### ISSUE THREAD

**Issue by longzeyilang** [WXinlong/SOLO#21]
I use a picture to detect, the model is Decoupled_SOLO_Light_R50_3x and the default config. the inference time cost two much time,about 0.6 sec,why?

**Comment by WXinlong** [comment]
@longzeyilang  Can you provide your script used to test the speed?

**Comment by longzeyilang** [comment]
use default config. And nvidia is 1080ti

**Comment by WXinlong** [comment]
@longzeyilang  I mean how you test the speed. It looks like you test through the demo script, which includes additional initialization and processing steps like model loading and visualization part.

**Comment by longzeyilang** [comment]
https://github.com/WXinlong/SOLO/blob/master/demo/inference_demo.py

**Comment by WXinlong** [comment]
@longzeyilang  The inference speed should be tested in test_ins.py, not the inference_demo.py, due to the reasons stated above.

**Comment by longzeyilang** [comment]
what is difference?

**Comment by WXinlong** [comment]
@longzeyilang  The inference_demo.py includes additional initialization and processing steps like model loading and visualization part.
