### ISSUE TITLE
solo训练mAP上不去

### ISSUE THREAD

**Issue by njustczr** [WXinlong/SOLO#224]
我是单卡，batch-size最大设为4，训练solo或者d-solo，mask-AP只能到0.25左右
我直接训练mask-rcnn  mask-AP能到0.44
我训练的是MVTEC D2C商品数据集，训练集4380张 验证集3600张
d-solo我把grid设为80, 72, 48, 32, 24，  mask-AP最多到0.25左右
scale_ranges 我理解是mask的面积，设置翻倍，也没什么效果，作者能给点啥建议吗？

**Comment by njustczr** [comment]
已经找到原因了，分析了一下这个数据集，训练集物体个数是相对比较少，且比较大的，所以调小grid，8个epoch的时候，d-solo mask-AP 验证集已经达到0.368了  （数据集60个类别）

**Comment by blurmemo** [comment]
> 已经找到原因了，分析了一下这个数据集，训练集物体个数是相对比较少，且比较大的，所以调小grid，8个epoch的时候，d-solo mask-AP 验证集已经达到0.368了 （数据集60个类别）

你好可以分享一下你自定义数据集的相关配置吗？我的vx是15333768199，目前也在用solov2训练我自己的数据集
