### ISSUE TITLE
Model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by HuygheB** [WXinlong/SOLO#225]
When starting up my training I get the following warning: 

2022-04-27 20:12:38,722 - mmdet - WARNING - The model and loaded state dict do not match exactly    
unexpected key in source state_dict: fc.weight, fc.bias    

I'm guessing it has something to do with the checkpoint file.

**Comment by songyangsun** [comment]
me too, but if you load backbone pretrain and model pretrain successfully, there is no much influence.
