### ISSUE TITLE
How to test after one epoch？

### ISSUE THREAD

**Issue by songyangsun** [WXinlong/SOLO#226]
now,only test at last. How to test after one epoch？

**Comment by HuygheB** [comment]
@songyangsun have you found a method to do it?

**Comment by hiiro0420** [comment]
if you use configs/solo/solo_r50_fpn_8gpu_1x.py, you change "woriflow = [('train',1),('val',1)]"  in configs/solo/solo_r50_fpn_8gpu_1x.py.

**Comment by hiiro0420** [comment]
https://mmcv.readthedocs.io/en/latest/understand_mmcv/runner.html#epochbasedrunner
is very useful

**Comment by songyangsun** [comment]
i try it

**Comment by songyangsun** [comment]
> if you use configs/solo/solo_r50_fpn_8gpu_1x.py, you change "workflow = [('train',1),('val',1)]" in configs/solo/solo_r50_fpn_8gpu_1x.py.

I try it,but it can't do eval in SOLO. Can you do eval and print mAP result?

**Comment by songyangsun** [comment]
> > if you use configs/solo/solo_r50_fpn_8gpu_1x.py, you change "workflow = [('train',1),('val',1)]" in configs/solo/solo_r50_fpn_8gpu_1x.py.
> 
> I try it,but it can't do eval in SOLO. Can you do eval and print mAP result?

I use mmdetection to solve it,please refer to it.
