### ISSUE TITLE
Question about training a model

### ISSUE THREAD

**Issue by Fly-dream12** [WXinlong/SOLO#24]
When I try to train this model, this error happens.

../mmdet/models/anchor_heads/solo_head.py", line 203, in loss
    num_ins = flatten_ins_ind_labels.sum()
RuntimeError: "sum_cuda" not implemented for 'Bool'

i have run 'python setup.py build_ext --inplace'

**Comment by WXinlong** [comment]
@Fly-dream12  It looks like it is not installed properly.  Can you provide your environment details and check your installation?

**Comment by Fly-dream12** [comment]
I have changed it to cpu tensor. 
The installation is right and my environment is under cuda 9.2, torch1.1.0, torchvision 0.2.2.

**Comment by taokong** [comment]
@Fly-dream12 check the data type of 'flatten_ins_ind_labels'? If it is bool, try converting it to int?

**Comment by cizhenshi** [comment]
> @Fly-dream12 check the data type of 'flatten_ins_ind_labels'? If it is bool, try converting it to int?

I meet the same problem, and it works. Thanks!
