### ISSUE TITLE
How to inference on a single image？

### ISSUE THREAD

**Issue by oukohou** [WXinlong/SOLO#3]
Sorry to bother, but I'm not familiar with mmdetection, so what if I want to inference a single image instead of the coco test set?
Thanks in advance~

**Comment by WXinlong** [comment]
@oukohou  A quick demo is available at [https://github.com/WXinlong/SOLO/blob/master/demo/inference_demo.py](url).
You can download the provided models and inference on your own single image.

**Comment by oukohou** [comment]
@WXinlong Thanks for timely reply，I‘ve tried the demo and goes smoothly~~
