### ISSUE TITLE
Question about CoordConv

### ISSUE THREAD

**Issue by BIYTC** [WXinlong/SOLO#34]
I don't understand how to put "two or more layers of CoordConv" in your network in Table4.
e.i. I want to know what's the position of another CoordConv in this network.
我不知道您在做table4的实验的时候CoordConv都加在那哪了，为什么可以加1个以上的CoordConv？

**Comment by WXinlong** [comment]
@BIYTC  For the second CoordConv, just concatenate another  2-channel coordinate map for the second conv in head.
