### ISSUE TITLE
可以简单讲解下gt_areas和hit_indices的计算原理吗？

### ISSUE THREAD

**Issue by XuDongHecs** [WXinlong/SOLO#38]
训练自己数据的时候遇到一些报错，调试发现不理解这个原理。
您可以简单讲解下吗？

**Comment by WXinlong** [comment]
@XuDongHecs   It's for assigning objects to different fpn levels according to their areas.

**Comment by yoonjaecho** [comment]
Hi @WXinlong,

As I know, the format of `gt_bboxes_row` is (x, y, w, h), but I couldn't understand the below code.

https://github.com/WXinlong/SOLO/blob/d5398a0d8d4ff30384058783fe5edfff24a8dcf2/mmdet/models/anchor_heads/solo_head.py#L243-L244
What is the exact meaning of the `gt_areas = sqrt((w - x) * (h - y))`?
