### ISSUE TITLE
Get stuck on loading resnet50

### ISSUE THREAD

**Issue by Wei-Mao** [WXinlong/SOLO#41]
I train with 4 GPUs by the command
./tools/dist_train.sh configs/solo/solo_r50_fpn_8gpu_1x.py 4
But the process can not proceede after  reaching 
2020-05-02 15:26:02,261 - mmdet - INFO - load model from: torchvision://resnet50

However, when I train with 1 GPU on another machine, the resnet50 can be loaded properly.
Could you help me out?

**Comment by WXinlong** [comment]
@Wei-Mao   It looks like the res50 model was not smoothly downloaded on that machine.  You can download the model yourself, put it under a directory and change the config file (L4), e.g., change `pretrained='torchvision://resnet50' `to  `pretrained=xxxx`

**Comment by Wei-Mao** [comment]
Thanks a lot!
