### ISSUE TITLE
9 fps of decoupled_solo_light_dcn_release_r50_fpn_8gpu_3 on GTX 1080 Ti

### ISSUE THREAD

**Issue by Harut0726** [WXinlong/SOLO#49]
I trained decoupled_solo_light_dcn_release_r50_fpn_8gpu_3x.py on my own data with default config (only changed path to data and number of classes). When I tried to run the model on video, it gave 8-9 fps on average instead of 20 that was in the paper. What is the reason?
To calculate avg FPS I just ran inference_detector() for every frame in the video without any post-processing.

**Comment by WXinlong** [comment]
@Harut0726  The inference_detector() includes pre-processing. You can refer to [inference.py](https://github.com/WXinlong/SOLO/blob/d5398a0d8d4ff30384058783fe5edfff24a8dcf2/mmdet/apis/inference.py#L65) for details.
