### ISSUE TITLE
Scale setting of FPN assignment

### ISSUE THREAD

**Issue by txytju** [WXinlong/SOLO#50]
Thanks for your great work! In Table-3 of SOLO paper, why scale of FPN levels overlaps with each other? And Why do you re-scale P2 to size of P3? Thanks!

**Comment by WXinlong** [comment]
@txytju  It follows the settings of FoveaBox. About P2 features, it's for reducing the GPU memory of mask branch.

**Comment by hogeman2** [comment]
@WXinlong is there any reason you changed you set base area larger?

**Comment by WXinlong** [comment]
@txytju  As mentioned, we didn't change the scale range. Other settings can also be used, but we didn't test it.
