### ISSUE TITLE
Question about GPU batch computation

### ISSUE THREAD

**Issue by sukjunhwang** [WXinlong/SOLO#52]
I have a question about how the code of this repo is forwarding a batch.

If I am correctly understood, seems like it's taking out a single image related instances from batch, compute, and gather loss at the end.

Would the training time take a bit longer than forwarding the whole batch as one?
Is there a difference of performance if batch is forwarded as a whole by adding some zero padding?

**Comment by WXinlong** [comment]
@nalbwa  On each GPU, the inputs are padded to a batch. For more details, you can refer to [mmdetection](https://github.com/open-mmlab/mmdetection).
