### ISSUE TITLE
模型名称的含义,1x,2x

### ISSUE THREAD

**Issue by kaijieshi7** [WXinlong/SOLO#53]
模型最后加个1x,2x。是啥意思啊。

**Comment by zehuichen123** [comment]
lr schedule, 1x means 12epoch, decay at 8 and 11. 2x means 24epoch, decay at 16 and 22.

**Comment by kaijieshi7** [comment]
哦哦，你这么一说，我想起来好多都是12为基数的，是有什么特殊的原因吗？还是大家都这样做

**Comment by zehuichen123** [comment]
后者
