### ISSUE TITLE
Question about label index and category prediction num

### ISSUE THREAD

**Issue by zehuichen123** [WXinlong/SOLO#54]
Hi, I am trying to apply SOLO on my own dataset which works pretty good. 
However, when I check the dimension of category prediction, I notice that your code predict the exact number of category w/o bg. Say if we have 80 classes in coco, your category branch will only predict 80 dim arrays, however, the categorical labels may range from 0 ~ 81. So how can they work well in cross entropy loss? Did I miss something?

**Comment by zehuichen123** [comment]
Sorry, the loss is focal loss, not cross entropy.

**Comment by ChenyuLy** [comment]
Have you solved this problem?
