### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by kaijieshi7** [WXinlong/SOLO#55]
mmdetection现在是2.0的版本了，安装的也是2.0的版本的。您的代码需要做对应的修改吗？

**Comment by kaijieshi7** [comment]
在cuda10.1上面测试过了？那pytorch是什么版本呢？

**Comment by kaijieshi7** [comment]
我已经解决了，我的cuda是10.1版本的，下了对应的1.3的torch和0.4的torchvision，重新安装就可以了

**Comment by yoyoshuang** [comment]
@kaijieshi7 请问你是否在mmdetection 2.0版本下运行成功solov2了吗？只是torch和torchvision 版本对应好就可以吗？是否需要修改作者原始代码吗？
