### ISSUE TITLE
cannot import name "deform_conv_cuda"

### ISSUE THREAD

**Issue by XDhughie** [WXinlong/SOLO#58]
SOLO\mmdet\ops\dcn\deform_conv.py", line 10, in <module>
    from .src import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn.src' (unknown location)

**Comment by WXinlong** [comment]
@XDhughie  Please check the installation.

**Comment by Puzzle0612** [comment]
Solved mine by downloading pytorch with -c pytorch rather than other conda sources
