### ISSUE TITLE
what do u mean by “Light-weight models”

### ISSUE THREAD

**Issue by MengHao666** [WXinlong/SOLO#6]
For example， what‘s the differences between “Decoupled_SOLO_R50_3x” and “DECOUPLED_SOLO_LIGHT_R50_3x”？

**Comment by WXinlong** [comment]
@MengHao666  The light-weight models use smaller input size, less stacked convs in the head, and a merge of x-branch and y-branch in Decoupled SOLO.  The details can be referred to the [config file](https://github.com/WXinlong/SOLO/blob/master/configs/solo/decoupled_solo_light_r50_fpn_8gpu_3x.py).
