### ISSUE TITLE
模型性能

### ISSUE THREAD

**Issue by jianpursuit** [WXinlong/SOLO#60]
请问这里给出的模型的精度是不是比paper上的低一些？

**Comment by WXinlong** [comment]
@jianpursuit  Hi, the results are consistent or better than those reported in the paper, e.g., 36.4 ap vs 35.8 ap for decoupled_solo_r50_3x model reported here and in the paper.

**Comment by jianpursuit** [comment]
oh i see thank you!

**Comment by jinfagang** [comment]
@WXinlong Does solov2 now included in this repo?

**Comment by WXinlong** [comment]
@jinfagang  Not yet.

**Comment by ceciliaAI** [comment]
Looking forward  solov2

**Comment by deep-practice** [comment]
@WXinlong When will be solov2 ready?

**Comment by WXinlong** [comment]
Hi all, SOLOv2 is released.:)
