### ISSUE TITLE
the function get_masks(result, num_classes=80) in test_ins.py

### ISSUE THREAD

**Issue by zhangyingbit** [WXinlong/SOLO#62]
Thanks for the great work~
when I test my trained model, I find the function "get_masks(result, num_classes=80)" in test_ins.py is very time-consuming，about  0.285533s/image, I think it is just for preparing result for evaluation mAP,  am I right?

**Comment by WXinlong** [comment]
@zhangyingbit  Yes, you are right. It should not be considered for the speed test.

**Comment by zhangyingbit** [comment]
@WXinlong Thanks for your reply~
