### ISSUE TITLE
mmdetection2.0 compatibility?

### ISSUE THREAD

**Issue by jinfagang** [WXinlong/SOLO#64]
Will it upgrade to mmdetection 2.0? (it fixed a lot of plugin issues in mmdetection 2.0 if using pytorch1.5)

**Comment by WXinlong** [comment]
@jinfagang  Yes, it's almost done. I will release it later.

**Comment by jinfagang** [comment]
@WXinlong waiting for your updates

**Comment by IIAT-MR-LL** [comment]
@WXinlong Hello, is any plan that SOLOv2 is compatible with mmdetection 2.0 recently?

**Comment by WXinlong** [comment]
Please refer to this [PR](https://github.com/open-mmlab/mmdetection/pull/3447), or https://github.com/WXinlong/mmdetection/tree/SOLO.
