### ISSUE TITLE
How to use random crop when training?

### ISSUE THREAD

**Issue by zacario-li** [WXinlong/SOLO#69]
How to use random crop when training?
Cause I need to reduce GPU memory cost.

**Comment by WXinlong** [comment]
You can customize the [training pipeline.](https://github.com/WXinlong/SOLO/blob/5c4dfd0291d32043ebab1daedc24f15cc721dde2/configs/solov2/solov2_r50_fpn_8gpu_3x.py#L63)  
If just for reducing the GPU memory,  you can just set a smaller image scale.

**Comment by zacario-li** [comment]
@WXinlong so in "training pipeline", I saw there is "resize" and "randomcrop". Does "resize" do before "randomcrop"?
If I want just to do "randomcrop" without "resize", how to do it?

**Comment by WXinlong** [comment]
@zacario-li  There is no "randomcrop" in our config file. If you want to use random crop, please see [this file](https://github.com/WXinlong/SOLO/blob/5c4dfd0291d32043ebab1daedc24f15cc721dde2/mmdet/datasets/pipelines/transforms.py).
