### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by MengHao666** [WXinlong/SOLO#7]
when i try run command：python demo/webcam_demo.py configs/solo/solo_r50_fpn_8gpu_3x.py checkpoints/SOLO_R50_3x.pth 

i got the error :
Press "Esc", "q" or "Q" to exit.
Traceback (most recent call last):
  File "demo/webcam_demo.py", line 47, in <module>
    main()
  File "demo/webcam_demo.py", line 43, in main
    show_result(img, result, model.CLASSES, score_thr=args.score_thr, wait_time=1)
  File "/home/haomeng/PycharmProjects/SOLO/mmdet/apis/inference.py", line 155, in show_result
    for i, bbox in enumerate(bbox_result)
  File "/home/haomeng/PycharmProjects/SOLO/mmdet/apis/inference.py", line 155, in <listcomp>
    for i, bbox in enumerate(bbox_result)
AttributeError: 'tuple' object has no attribute 'shape'

**Environment**
just follow the install.md  : pip install -v -e .[all]

**Comment by taokong** [comment]
@MengHao666 Here [inference_demo.py](https://github.com/WXinlong/SOLO/blob/master/demo/inference_demo.py) gives a demo on how to inference a single image. Don't use the webcam_demo.py which is not suitable for SOLO. We will give correct webcam_demo as soon as possible.

**Comment by MengHao666** [comment]
oui,merci beaucoup.
