### ISSUE TITLE
CUDA out of memory when trying to inference SOLOv2

### ISSUE THREAD

**Issue by bowenc0221** [WXinlong/SOLO#70]
I tried to run inference of SOLOv2 using the command `python tools/test.py configs/solov2/solov2_r101_dcn_fpn_8gpu_3x.py model_zoo/solov2_r101_dcn_fpn_8gpu_3x.pth --eval segm --json_out coco_json/solov2_r101_dcn_fpn_8gpu_3x_coco_val_results` but I got CUDA out of memory error after evaluating around 1000 images.

Has anyone encountered this problem as well?

**Comment by WXinlong** [comment]
@bowenc0221  Did you use tools/test_ins.py?

**Comment by bowenc0221** [comment]
I tried tools/test_ins.py but got the following error:

```
  File "tools/test_ins.py", line 257, in <module>
    main()
  File "tools/test_ins.py", line 248, in main
    results2json(dataset, outputs, args.json_out)
  File "SOLO/mmdet/core/evaluation/coco_utils.py", line 224, in results2json
    json_results = det2json(dataset, results)
  File "SOLO/mmdet/core/evaluation/coco_utils.py", line 153, in det2json
    for i in range(bboxes.shape[0]):
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by WXinlong** [comment]
@bowenc0221  I see. Please run without  --json_out: `python tools/test_ins.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --show --out  ${OUTPUT_FILE} --eval segm`. It also saves the output json file.

**Comment by bowenc0221** [comment]
Thanks
