### ISSUE TITLE
mmdetection version 2

### ISSUE THREAD

**Issue by xuanthuyvo** [WXinlong/SOLO#75]
When will you integrate your method into mmdetection version 2?

**Comment by qianzhang613** [comment]
Did there are any plan to switch mmdetection version 2?

**Comment by jinfagang** [comment]
I have a fork version supports mmdetection2 also fixed some custom dataset training bug such as cityscapes.

**Comment by xuanthuyvo** [comment]
@jinfagang Could you share this link?

**Comment by jinfagang** [comment]
http://manaai.cn/aicodes_detail3.html?id=61

**Comment by xuanthuyvo** [comment]
Thank you so much!

**Comment by WXinlong** [comment]
Please refer to this [PR](https://github.com/open-mmlab/mmdetection/pull/3447), or https://github.com/WXinlong/mmdetection/tree/SOLO.

**Comment by cyrilzakka** [comment]
@jinfagang I can't seem to find it on Github. Would you mind sharing it?
