### ISSUE TITLE
About Uniﬁed mask feature branch

### ISSUE THREAD

**Issue by ntuLC** [WXinlong/SOLO#76]
Hi, I just read the SOLOv2 paper and found it very inspiring. But I got a question when I read the code

In `mmdet/models/anchor_heads/solov2_head.py`:

```python
    def forward(self, feats, eval=False):
        new_feats = self.split_feats(feats)
        featmap_sizes = [featmap.size()[-2:] for featmap in new_feats]
        upsampled_size = (featmap_sizes[0][0] * 2, featmap_sizes[0][1] * 2)
        cate_pred, kernel_pred = multi_apply(self.forward_single, new_feats,
                                                       list(range(len(self.seg_num_grids))),
                                                       eval=eval, upsampled_size=upsampled_size)
        return cate_pred, kernel_pred
```

It seems that the code still uses different mask encoders and grid numbers for feature of each FPN level. Is the Uniﬁed mask feature branch function mentioned in the SOLOv2 paper included in the code? Or are there any settings related?

Thank you!

**Comment by taokong** [comment]
@ntuLC please refer to [mask_feat_head.py](https://github.com/WXinlong/SOLO/blob/master/mmdet/models/mask_heads/mask_feat_head.py)

**Comment by ntuLC** [comment]
> @ntuLC please refer to [mask_feat_head.py](https://github.com/WXinlong/SOLO/blob/master/mmdet/models/mask_heads/mask_feat_head.py)

Thanks for your suggestion! 

So If my understanding was correct, the "Unified mask feature representation" means that different FPN levels are only fused when producing the mask feature, but other structures, including kernel branches and category branches, are still separate for each FPN level. Then these separate kernel branches and category branches are applied on the same unified mask feature. In other words, there are still multiple category branches, performing on each FPN level. Is this correct?

**Comment by taokong** [comment]
Yes.  
Each FPN level has its category branch for dealing corresponding instance scales, and the weights are shared among them.

**Comment by ntuLC** [comment]
Ok, I got it. Thank you again, @taokong!
