### ISSUE TITLE
RuntimeError with multi GPU training

### ISSUE THREAD

**Issue by shwoo93** [WXinlong/SOLO#8]
Thanks for sharing your nice code.

I meet the following error when I attempt to train the SOLO using multiple GPUs.
(i.e., tools/dist_train.sh configs/solo/decoupled_solo_r50_fpn_8gpu_3x.py 8)

**Environment**
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-16GB
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.5.0
OpenCV: 4.1.0
MMCV: 0.4.2
MMDetection: 1.0.0+925cc7c
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0

**Error traceback**
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 121, in main
    timestamp=timestamp)
  File "/home/ubuntu/SOLO/mmdet/apis/train.py", line 103, in train_detector
    timestamp=timestamp)
  File "/home/ubuntu/SOLO/mmdet/apis/train.py", line 253, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/SOLO/mmcv/mmcv/runner/runner.py", line 359, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/SOLO/mmcv/mmcv/runner/runner.py", line 263, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/ubuntu/SOLO/mmdet/apis/train.py", line 78, in batch_processor
    losses = model(**data)
  File "/home/ubuntu/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 464, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /opt/conda/conda-bld/pytorch_1579040055865/work/torch/csrc/distributed/c10d/reducer.cpp:514)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f1a30bf9627 in /home/ubuntu/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0x7b7 (0x7f1a672cc557 in /home/ubuntu/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0xa39bd1 (0x7f1a672b7bd1 in /home/ubuntu/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x28ba06 (0x7f1a66b09a06 in /home/ubuntu/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyMethodDef_RawFastCallKeywords + 0x264 (0x56045afec114 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #5: _PyCFunction_FastCallKeywords + 0x21 (0x56045afec231 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x52cf (0x56045b050e8f in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #7: _PyEval_EvalCodeWithName + 0x2f9 (0x56045afa56f9 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #8: _PyFunction_FastCallDict + 0x400 (0x56045afa6a30 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #9: _PyObject_Call_Prepend + 0x63 (0x56045afc1943 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #10: PyObject_Call + 0x6e (0x56045afb4b9e in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x1e35 (0x56045b04d9f5 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2f9 (0x56045afa56f9 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #13: _PyFunction_FastCallDict + 0x400 (0x56045afa6a30 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #14: _PyObject_Call_Prepend + 0x63 (0x56045afc1943 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #15: <unknown function> + 0x17512a (0x56045b00012a in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #16: PyObject_Call + 0x6e (0x56045afb4b9e in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x1e35 (0x56045b04d9f5 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x2f9 (0x56045afa56f9 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #19: _PyFunction_FastCallDict + 0x400 (0x56045afa6a30 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x1e35 (0x56045b04d9f5 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x2f9 (0x56045afa56f9 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #22: _PyFunction_FastCallDict + 0x1d5 (0x56045afa6805 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #23: _PyObject_Call_Prepend + 0x63 (0x56045afc1943 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #24: PyObject_Call + 0x6e (0x56045afb4b9e in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x1e35 (0x56045b04d9f5 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #26: _PyEval_EvalCodeWithName + 0x2f9 (0x56045afa56f9 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #27: _PyFunction_FastCallKeywords + 0x387 (0x56045afeb917 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x6a0 (0x56045b04c260 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #29: _PyEval_EvalCodeWithName + 0xc30 (0x56045afa6030 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #30: _PyFunction_FastCallKeywords + 0x387 (0x56045afeb917 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x14e6 (0x56045b04d0a6 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #32: _PyEval_EvalCodeWithName + 0x2f9 (0x56045afa56f9 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #33: _PyFunction_FastCallKeywords + 0x387 (0x56045afeb917 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x14e6 (0x56045b04d0a6 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #35: _PyFunction_FastCallKeywords + 0xfb (0x56045afeb68b in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x416 (0x56045b04bfd6 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #37: _PyEval_EvalCodeWithName + 0x2f9 (0x56045afa56f9 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #38: PyEval_EvalCodeEx + 0x44 (0x56045afa65f4 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #39: PyEval_EvalCode + 0x1c (0x56045afa661c in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #40: <unknown function> + 0x21c974 (0x56045b0a7974 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #41: PyRun_FileExFlags + 0xa1 (0x56045b0b1cf1 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #42: PyRun_SimpleFileExFlags + 0x1c3 (0x56045b0b1ee3 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #43: <unknown function> + 0x227f95 (0x56045b0b2f95 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #44: _Py_UnixMain + 0x3c (0x56045b0b30bc in /home/ubuntu/anaconda3/envs/mmdet/bin/python)
frame #45: __libc_start_main + 0xf0 (0x7f1a6c753830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #46: <unknown function> + 0x1d0990 (0x56045b05b990 in /home/ubuntu/anaconda3/envs/mmdet/bin/python)

**Comment by taokong** [comment]
@shwoo93 Try pull and reinstall the latest SOLO? #10

**Comment by shwoo93** [comment]
Thanks for your advice. The issue has been resolved now :)
