### ISSUE TITLE
webcam_demo.py failed because 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by jameslele** [WXinlong/SOLO#82]
File "/SOLO/demo/webcam_demo.py", line 44, in <module>
    main()
  File "/SOLO/demo/webcam_demo.py", line 38, in main
    img, result, model.CLASSES, score_thr=args.score_thr, wait_time=1)
  File "/SOLO/mmdet/apis/inference.py", line 160, in show_result
    for i, bbox in enumerate(bbox_result)
  File "/SOLO/mmdet/apis/inference.py", line 160, in <listcomp>
    for i, bbox in enumerate(**bbox_result**)
**AttributeError: 'tuple' object has no attribute 'shape'**

Even I take a image as input(which runs well at inference_demo.py), this error will also arise. 

Thank you in advance!

**Comment by WXinlong** [comment]
@jameslele  Hi, the webcam is not supported yet. Please use demo/inference_demo.py  for a simple demo.

**Comment by jameslele** [comment]
@WXinlong Ok, thanks.

**Comment by Fyijun** [comment]
I encountered the same error as you, did you solve it？(runs the inference_demo.py, not webcam_demo.py)
