### ISSUE TITLE
config: num_classes in the mask_feat_head

### ISSUE THREAD

**Issue by edwardnguyen1705** [WXinlong/SOLO#83]
Dear @WXinlong ,
Thanks for sharing your work.
I have no idea what is the `num_classes` in the `mask_feat_head`
https://github.com/WXinlong/SOLO/blob/5c4dfd0291d32043ebab1daedc24f15cc721dde2/configs/solov2/solov2_light_512_dcn_r50_fpn_8gpu_3x.py#L52

Could you please elaborate a bit?

**Comment by WXinlong** [comment]
@edwardnguyen1705  It means the output channel of the mask feature branch. I didn't rename it, sorry for the ambiguity.

**Comment by edwardnguyen1705** [comment]
@WXinlong Thanks for your quick response. I got it.
