### ISSUE TITLE
Config for evaluating a custom dataset

### ISSUE THREAD

**Issue by edwardnguyen1705** [WXinlong/SOLO#84]
Dear @WXinlong ,

After training on a custom dataset (inherited from the `CocoDataset`, just like the way in the `cityscapes.py`), the visualization looks great, but mAP = 0.  I see in the `test_insts.py`
`coco_eval(result_file, eval_types, dataset.coco)`

Is it the right way?

**Comment by jinfagang** [comment]
I think `dataset.coco` means the object of `COCO`. which is your loaded coco format dataset. it can be considerate as ground truth coco for evaluation.

**Comment by jinfagang** [comment]
for CustomDataset evaluation got mAP=0, check the annotation iscrowd enable or not, if you using RLE for representation of segmentation mask, you should enable iscrowd=1 when calculate mask iou

**Comment by edwardnguyen1705** [comment]
@jinfagang 
Thanks for sharing.

> for CustomDataset evaluation got mAP=0, check the annotation iscrowd enable or not, if you using RLE for representation of segmentation mask, you should enable iscrowd=1 when calculate mask iou

I do not quite understand this one.

**Comment by jinfagang** [comment]
@edwardnguyen1705 coco loadRes will force iscrowd to false. You can take a close look at coco evaluation code.

**Comment by edwardnguyen1705** [comment]
@jinfagang ,
Thank you for your response.

**Comment by haibucuo0** [comment]
@edwardnguyen1705 ,how to modify test_ins.py when I use own data？thanks

**Comment by edwardnguyen1705** [comment]
@haibucuo0 you can take a look at my fork: [solo](https://github.com/edwardnguyen1705/SOLO/blob/mvtecd2s-obj-strong/run_test_ins.sh)
