### ISSUE TITLE
 Why did the SOLOV2 source code is different from the paper implementation?

### ISSUE THREAD

**Issue by Liusandian** [WXinlong/SOLO#89]
https://github.com/WXinlong/SOLO/blob/5c4dfd0291d32043ebab1daedc24f15cc721dde2/mmdet/models/anchor_heads/solov2_head.py#L152

Thank you for the source code contribution.

When I compared the SOLOv2 paper with the source code, I found a problem; the mask generated by the solov2 head in the original paper is through learning the convolution kernel G, and the other branch is the Unified mask feature branch, which includes multiple upsample modules, but in your In the official code of solov2_head, I did not see the realization of this part of the process, and also the element-wise summation step.

However, I saw the complete solov2_head implementation in another version of the unofficial implementation（https://github.com/Epiphqny/SOLOv2/blob/master/mmdet/models/anchor_heads/solov2_head.py）(line in 81~240). Do you need to add the Unified mask feature branch module? Does your official code update solov2 represent predict the mask feature for each FPN levels?
I am looking forward to your reply,thanks!

**Comment by taokong** [comment]
please refer to [mask_feat_head.py](https://github.com/WXinlong/SOLO/blob/master/mmdet/models/mask_heads/mask_feat_head.py)
