### ISSUE TITLE
How to get the inference time correctly

### ISSUE THREAD

**Issue by jcdubron** [WXinlong/SOLO#92]
Does the testing time in tables contain data loading?
If not, how to get the inference time correctly?

**Comment by still-wait** [comment]
@jcdubron How did you solve this problem? Infer time i got in v100 is not correctly.

**Comment by jcdubron** [comment]
I use the [benchmark.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/benchmark.py) provided in the latest version of mmdetection. But I'm not sure if it's accurate because I have no v100.
