### ISSUE TITLE
Got an error while installing the setup, all the versions of the requirements are fulfilled, kindly suggest me a solution

### ISSUE THREAD

**Issue by abubakar2141731** [WXinlong/SOLO#97]
Using pip 20.2.2 from /usr/local/envs/solo/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-5oax48bq
Created temporary directory: /tmp/pip-req-tracker-kl6_rm72
Initialized build tracking at /tmp/pip-req-tracker-kl6_rm72
Created build tracker: /tmp/pip-req-tracker-kl6_rm72
Entered build tracker: /tmp/pip-req-tracker-kl6_rm72
Created temporary directory: /tmp/pip-install-6hs_tvlx
Obtaining file:///content/SOLO
  Added file:///content/SOLO to build tracker '/tmp/pip-req-tracker-kl6_rm72'
    Running setup.py (path:/content/SOLO/setup.py) egg_info for package from file:///content/SOLO
    Created temporary directory: /tmp/pip-pip-egg-info-l_9e4fsa
  Source in /content/SOLO has version 1.0.0+5c4dfd0, which satisfies requirement mmdet==1.0.0+5c4dfd0 from file:///content/SOLO
  Removed mmdet==1.0.0+5c4dfd0 from file:///content/SOLO from build tracker '/tmp/pip-req-tracker-kl6_rm72'
  Installing extra requirements: 'all'
Requirement already satisfied: matplotlib in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (3.3.1)
Requirement already satisfied: mmcv==0.2.16 in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (0.2.16)
Requirement already satisfied: numpy in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (1.19.1)
Requirement already satisfied: scipy in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (1.5.2)
Requirement already satisfied: Pillow<=6.2.2 in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (6.2.2)
Requirement already satisfied: six in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (1.15.0)
Requirement already satisfied: terminaltables in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (3.1.0)
Requirement already satisfied: torch>=1.1 in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (1.6.0)
Requirement already satisfied: torchvision in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (0.7.0)
Requirement already satisfied: albumentations>=0.3.2 in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (0.4.6)
Requirement already satisfied: imagecorruptions in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (1.1.0)
Requirement already satisfied: asynctest in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (0.13.0)
Requirement already satisfied: codecov in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (2.1.9)
Requirement already satisfied: flake8 in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (3.8.3)
Requirement already satisfied: isort in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (5.5.1)
Requirement already satisfied: pytest in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (6.0.1)
Requirement already satisfied: pytest-cov in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (2.10.1)
Requirement already satisfied: pytest-runner in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (5.2)
Requirement already satisfied: xdoctest>=0.10.0 in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (0.14.0)
Requirement already satisfied: yapf in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (0.30.0)
Requirement already satisfied: kwarray in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (0.5.9)
Requirement already satisfied: cython in /usr/local/envs/solo/lib/python3.7/site-packages (from mmdet==1.0.0+5c4dfd0) (0.29.21)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/envs/solo/lib/python3.7/site-packages (from matplotlib->mmdet==1.0.0+5c4dfd0) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/envs/solo/lib/python3.7/site-packages (from matplotlib->mmdet==1.0.0+5c4dfd0) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/envs/solo/lib/python3.7/site-packages (from matplotlib->mmdet==1.0.0+5c4dfd0) (2.8.1)
Requirement already satisfied: certifi>=2020.06.20 in /usr/local/envs/solo/lib/python3.7/site-packages (from matplotlib->mmdet==1.0.0+5c4dfd0) (2020.6.20)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/envs/solo/lib/python3.7/site-packages (from matplotlib->mmdet==1.0.0+5c4dfd0) (1.2.0)
Requirement already satisfied: pyyaml in /usr/local/envs/solo/lib/python3.7/site-packages (from mmcv==0.2.16->mmdet==1.0.0+5c4dfd0) (5.3.1)
Requirement already satisfied: addict in /usr/local/envs/solo/lib/python3.7/site-packages (from mmcv==0.2.16->mmdet==1.0.0+5c4dfd0) (2.2.1)
Requirement already satisfied: requests in /usr/local/envs/solo/lib/python3.7/site-packages (from mmcv==0.2.16->mmdet==1.0.0+5c4dfd0) (2.24.0)
Requirement already satisfied: opencv-python>=3 in /usr/local/envs/solo/lib/python3.7/site-packages (from mmcv==0.2.16->mmdet==1.0.0+5c4dfd0) (4.4.0.42)
Requirement already satisfied: future in /usr/local/envs/solo/lib/python3.7/site-packages (from torch>=1.1->mmdet==1.0.0+5c4dfd0) (0.18.2)
Requirement already satisfied: imgaug>=0.4.0 in /usr/local/envs/solo/lib/python3.7/site-packages (from albumentations>=0.3.2->mmdet==1.0.0+5c4dfd0) (0.4.0)
Requirement already satisfied: opencv-python-headless>=4.1.1 in /usr/local/envs/solo/lib/python3.7/site-packages (from albumentations>=0.3.2->mmdet==1.0.0+5c4dfd0) (4.4.0.42)
Requirement already satisfied: scikit-image>=0.15 in /usr/local/envs/solo/lib/python3.7/site-packages (from imagecorruptions->mmdet==1.0.0+5c4dfd0) (0.17.2)
Requirement already satisfied: coverage in /usr/local/envs/solo/lib/python3.7/site-packages (from codecov->mmdet==1.0.0+5c4dfd0) (5.2.1)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/envs/solo/lib/python3.7/site-packages (from flake8->mmdet==1.0.0+5c4dfd0) (1.7.0)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0 in /usr/local/envs/solo/lib/python3.7/site-packages (from flake8->mmdet==1.0.0+5c4dfd0) (2.2.0)
Requirement already satisfied: pycodestyle<2.7.0,>=2.6.0a1 in /usr/local/envs/solo/lib/python3.7/site-packages (from flake8->mmdet==1.0.0+5c4dfd0) (2.6.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /usr/local/envs/solo/lib/python3.7/site-packages (from flake8->mmdet==1.0.0+5c4dfd0) (0.6.1)
Requirement already satisfied: py>=1.8.2 in /usr/local/envs/solo/lib/python3.7/site-packages (from pytest->mmdet==1.0.0+5c4dfd0) (1.9.0)
Requirement already satisfied: iniconfig in /usr/local/envs/solo/lib/python3.7/site-packages (from pytest->mmdet==1.0.0+5c4dfd0) (1.0.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/envs/solo/lib/python3.7/site-packages (from pytest->mmdet==1.0.0+5c4dfd0) (8.5.0)
Requirement already satisfied: packaging in /usr/local/envs/solo/lib/python3.7/site-packages (from pytest->mmdet==1.0.0+5c4dfd0) (20.4)
Requirement already satisfied: toml in /usr/local/envs/solo/lib/python3.7/site-packages (from pytest->mmdet==1.0.0+5c4dfd0) (0.10.1)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/envs/solo/lib/python3.7/site-packages (from pytest->mmdet==1.0.0+5c4dfd0) (0.13.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/envs/solo/lib/python3.7/site-packages (from pytest->mmdet==1.0.0+5c4dfd0) (20.2.0)
Requirement already satisfied: pandas in /usr/local/envs/solo/lib/python3.7/site-packages (from kwarray->mmdet==1.0.0+5c4dfd0) (1.1.1)
Requirement already satisfied: ubelt in /usr/local/envs/solo/lib/python3.7/site-packages (from kwarray->mmdet==1.0.0+5c4dfd0) (0.9.2)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/envs/solo/lib/python3.7/site-packages (from requests->mmcv==0.2.16->mmdet==1.0.0+5c4dfd0) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/envs/solo/lib/python3.7/site-packages (from requests->mmcv==0.2.16->mmdet==1.0.0+5c4dfd0) (1.25.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/envs/solo/lib/python3.7/site-packages (from requests->mmcv==0.2.16->mmdet==1.0.0+5c4dfd0) (3.0.4)
Requirement already satisfied: Shapely in /usr/local/envs/solo/lib/python3.7/site-packages (from imgaug>=0.4.0->albumentations>=0.3.2->mmdet==1.0.0+5c4dfd0) (1.7.1)
Requirement already satisfied: imageio in /usr/local/envs/solo/lib/python3.7/site-packages (from imgaug>=0.4.0->albumentations>=0.3.2->mmdet==1.0.0+5c4dfd0) (2.9.0)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/envs/solo/lib/python3.7/site-packages (from scikit-image>=0.15->imagecorruptions->mmdet==1.0.0+5c4dfd0) (1.1.1)
Requirement already satisfied: networkx>=2.0 in /usr/local/envs/solo/lib/python3.7/site-packages (from scikit-image>=0.15->imagecorruptions->mmdet==1.0.0+5c4dfd0) (2.5)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/envs/solo/lib/python3.7/site-packages (from scikit-image>=0.15->imagecorruptions->mmdet==1.0.0+5c4dfd0) (2020.9.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/envs/solo/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->flake8->mmdet==1.0.0+5c4dfd0) (3.1.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/envs/solo/lib/python3.7/site-packages (from pandas->kwarray->mmdet==1.0.0+5c4dfd0) (2020.1)
Requirement already satisfied: ordered-set in /usr/local/envs/solo/lib/python3.7/site-packages (from ubelt->kwarray->mmdet==1.0.0+5c4dfd0) (4.0.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/envs/solo/lib/python3.7/site-packages (from networkx>=2.0->scikit-image>=0.15->imagecorruptions->mmdet==1.0.0+5c4dfd0) (4.4.2)
Installing collected packages: mmdet
  Running setup.py develop for mmdet
Exception information:
Traceback (most recent call last):
  File "/usr/local/envs/solo/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/usr/local/envs/solo/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/envs/solo/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 421, in run
    pycompile=options.compile,
  File "/usr/local/envs/solo/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/usr/local/envs/solo/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 799, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/usr/local/envs/solo/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/usr/local/envs/solo/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/envs/solo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/SOLO/setup.py'"'"'; __file__='"'"'/content/SOLO/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-kl6_rm72'
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-l_9e4fsa/mmdet.egg-info
    writing /tmp/pip-pip-egg-info-l_9e4fsa/mmdet.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-l_9e4fsa/mmdet.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-l_9e4fsa/mmdet.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-l_9e4fsa/mmdet.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-l_9e4fsa/mmdet.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-l_9e4fsa/mmdet.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-l_9e4fsa/mmdet.egg-info/SOURCES.txt'
    Running command /usr/local/envs/solo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/SOLO/setup.py'"'"'; __file__='"'"'/content/SOLO/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    running build_ext
    building 'mmdet.ops.utils.compiling_info' extension
    Emitting ninja build file /content/SOLO/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    ninja: no work to do.
    g++ -pthread -shared -B /usr/local/envs/solo/compiler_compat -L/usr/local/envs/solo/lib -Wl,-rpath=/usr/local/envs/solo/lib -Wl,--no-as-needed -Wl,--sysroot=/ /content/SOLO/build/temp.linux-x86_64-3.7/mmdet/ops/utils/src/compiling_info.o -L/usr/local/envs/solo/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/mmdet/ops/utils/compiling_info.cpython-37m-x86_64-linux-gnu.so
    building 'mmdet.ops.nms.soft_nms_cpu' extension
    Emitting ninja build file /content/SOLO/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    ninja: no work to do.
    g++ -pthread -shared -B /usr/local/envs/solo/compiler_compat -L/usr/local/envs/solo/lib -Wl,-rpath=/usr/local/envs/solo/lib -Wl,--no-as-needed -Wl,--sysroot=/ /content/SOLO/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.7/mmdet/ops/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so
    building 'mmdet.ops.nms.nms_cpu' extension
    Emitting ninja build file /content/SOLO/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    ninja: no work to do.
    g++ -pthread -shared -B /usr/local/envs/solo/compiler_compat -L/usr/local/envs/solo/lib -Wl,-rpath=/usr/local/envs/solo/lib -Wl,--no-as-needed -Wl,--sysroot=/ /content/SOLO/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cpu.o -L/usr/local/envs/solo/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/mmdet/ops/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so
    building 'mmdet.ops.nms.nms_cuda' extension
    Emitting ninja build file /content/SOLO/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/1] c++ -MMD -MF /content/SOLO/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o.d -pthread -B /usr/local/envs/solo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/usr/local/envs/solo/lib/python3.7/site-packages/torch/include -I/usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/usr/local/envs/solo/lib/python3.7/site-packages/torch/include/TH -I/usr/local/envs/solo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/envs/solo/include/python3.7m -c -c /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp -o /content/SOLO/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /content/SOLO/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o
    c++ -MMD -MF /content/SOLO/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o.d -pthread -B /usr/local/envs/solo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/usr/local/envs/solo/lib/python3.7/site-packages/torch/include -I/usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/usr/local/envs/solo/lib/python3.7/site-packages/torch/include/TH -I/usr/local/envs/solo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/envs/solo/include/python3.7m -c -c /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp -o /content/SOLO/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp:2:
    /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for if ((end - begin) >= grain_size)

    /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp: In function ‘at::Tensor nms(const at::Tensor&, float)’:
    /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp:4:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                           ^
    /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(dets);
       ^~~~~~~~~~
    In file included from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                     from /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp:2:
    /usr/local/envs/solo/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
       DeprecatedTypeProperties & type() const {
                                  ^~~~
    /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^
    /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(dets);
       ^~~~~~~~~~
    /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^
    /content/SOLO/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(dets);
       ^~~~~~~~~~
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/usr/local/envs/solo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
        env=env)
      File "/usr/local/envs/solo/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/content/SOLO/setup.py", line 301, in <module>
        zip_safe=False)
      File "/usr/local/envs/solo/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/envs/solo/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/envs/solo/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/envs/solo/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/envs/solo/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/usr/local/envs/solo/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/local/envs/solo/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/envs/solo/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/envs/solo/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/usr/local/envs/solo/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/local/envs/solo/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/local/envs/solo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
        build_ext.build_extensions(self)
      File "/usr/local/envs/solo/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/usr/local/envs/solo/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/envs/solo/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/envs/solo/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/local/envs/solo/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/usr/local/envs/solo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/usr/local/envs/solo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/usr/local/envs/solo/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension
ERROR: Command errored out with exit status 1: /usr/local/envs/solo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/SOLO/setup.py'"'"'; __file__='"'"'/content/SOLO/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by cyrilzakka** [comment]
@abubakar2141731 @WXinlong how was this issue fixed? Currently running into the same problem during installation

**Comment by abubakar2141731** [comment]
Please refer to this notebook, 
it works for D2Det and Solo 
https://drive.google.com/file/d/162LkP8dbS-Acnr8XhMS9-RXGxS1zOpF7/view?usp=sharing
